config/routes.rb
BlogExample::Application.routes.draw do
  devise_for :usuarios
  resources :articles

   root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :usuario
	after_save :guardar_imagen
	acts_as_commentable
	PATH_IMAGENES = File.join Rails.root, 'public', 'imagenes_articulos'
	def photo=(archivo)
		unless archivo.blank?
			@archivo = archivo
			self.ext = archivo.original_filename.split('.').last.downcase
		end

	end
	def path_imagen 
		File.join PATH_IMAGENES, "#{self.id}.#{self.ext}"
	end
	def tiene_imagen?
		File.exists? path_imagen
	end
	private
	def guardar_imagen
		if @archivo
			FileUtils.mkdir_p PATH_IMAGENES
			File.open(path_imagen, 'wb') do |f|
				f.write(@archivo.read)
			end
			@archivo = nil
		end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :needs_session, except: [:show, :index]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_usuario.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:titulo, :contenido, :photo)
    end

    def needs_session
      redirect_to "/" unless usuario_signed_in?
    end
end

app/controllers/comments_controller.rb
class ArticlesController < ApplicationController
	
	def create
		comment = Comment.new(comment_params)
		commentable =  
	end

	private
	# Never trust parameters from the scary internet, only allow the white list through.

    def comment_params
      params.require(:comment).permit(:title, :comment)
    end
    def load_commentable
  		resource, id = request.path.split('/')[1, 2]
    	@commentable = resource.singularize.classify.constantize.find(id)	
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Artículos</h1>
<section id='articles'>
  <% @articles.each do |article| %>
    <div class="row">
      <div class="col-md-2 inline-middle">
        <% if article.tiene_imagen? %>
          <%= image_tag("/imagenes_articulos/#{article.id}.#{article.ext}") %>
        <%end%>
      </div>
      <div class="col-md-9 inline-middle">
        <h2><%= article.titulo %></h2>
        <% unless article.usuario.nil? %>
        <p>
          <strong>By: </strong> <%= article.usuario.email %>
        </p>
        <%end%>
        <p>
          <%= truncate(article.contenido, :length => 30) %>
        </p>
        <%= link_to "Leer", article, class: "btn btn-info" %>
      </div>
    </div>
  <%end%>

</section>
<!--
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.titulo %></td>
        <td><%= article.contenido %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->
<% if usuario_signed_in? %>
  <%= link_to 'New Article', new_article_path, class: "btn btn-danger" %>
<%else %>
  <p>Necesitas <%= link_to "estar registrado", new_usuario_registration_path %>.</p>
  <p>Si ya tienes cuenta, <%= link_to "inicia sesión", new_usuario_session_path %></p>
<%end%>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
 	<h1><%= @article.titulo %></h1>
 	<% if @article.tiene_imagen? %>
 		<%= image_tag("/imagenes_articulos/#{@article.id}.#{@article.ext}") %>
 	<%end%>
 	<p><%= @article.contenido %></p>
	<%= link_to 'Edit', edit_article_path(@article) %> |
	<%= link_to 'Back', articles_path %>
</div>
<section id="comments">
	<% @article.comments.each do |comment| %>
		<div class="media">
		  <a class="pull-left" href="#">
		    
		  </a>
		  <div class="media-body">
		    <h4 class="media-heading"><%= comment.title %></h4>
		    <p>
		    	<%= comment.comment %>
		    </p>
		  </div>
		</div>
	<%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<nav>
			<ul class="nav nav-tabs">
			  <li class="active"><a href="/">Inicio</a></li>
			  <li><a href="/articles">Articulos</a></li>
			  <% if usuario_signed_in? %>
			  	<li>
			  		<%= link_to "Log out", destroy_usuario_session_path, method: :delete %>
			  	</li>
			  <%else%>
			  	<li>
			  		<%= link_to "Log in", new_usuario_session_path%>
			  	</li>
			  <%end%>
			  
			</ul>
		</nav>
	</header>
	<p class="notice" style="<%= "display:none;" if notice.nil? %>"><%= notice %></p>
	<p class="alert" style="<%= "display:none;" if notice.nil? %>"><%= alert %></p>
	<%= yield %>

</body>
</html>